### ISSUE TITLE
Update Seimological Basic Skills

### ISSUE THREAD

**Issue by core-man** [MIGG-NTU/SeisTomo_Tutorials#5]
Hi Guys,

We can first update basic expertise and skills, seismology and seismic data sections.
Do you have any suggestion? Or which one do you want to work on?

**Comment by core-man** [comment]
We are preparing two tutorials **late Dec. 2020** or **Jan. 2021**:
- [Linux/maxOS & programming](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/)
- [seismology](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/) & [seismic data](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data)

We can first work on the first tutorial. Tianjue will work on [Commonly-used Commands](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/commonly-used-commands.html). There are another three sections needed to be worked on.
- [Operating System](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/operating-system.html)
- [Linux/macOS Basis and Command Lines](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/LinuxmacOS-basis-and-command-lines.html)
- [Prgramming Languages](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/prgramming-languages.html)

Do we have any volunteers for some of those sections? Of course, you can also help Tianjue with [Commonly-used Commands](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/commonly-used-commands.html).

**Comment by tianjueli** [comment]
I'd like to prepare the background materials to introduce seismic station in the later time from December.

**Comment by core-man** [comment]
thanks, tianjue for [seismic station](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-station.html). So, for the [seismology section](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/index.html#), we still have another three subsections,
- [earthquake catalog](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/earthquake-catalog.html)
- [seismic waveform](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-waveform.html)
- [seismological tools](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-tools.html)

For [seismic data](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/index.html#) sections, I plan three subsections,

- [data downloading](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/data-downloading/index.html)
- [data processing](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/data-processing/index.html)
- [plotting](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/plotting/index.html)

**Comment by HouseJaay** [comment]
I can do plotting and(or) data processing.
For the first tutorial, I think as the topic is general, how about just refer to good tutorial. For example:
https://missing.csail.mit.edu/
https://www.iris.edu/hq/inclass/course/roses

**Comment by core-man** [comment]
@HouseJaay  Thanks~ Yes, I agree with you. This is a **seismic tomographic** _tutorial_ instead of a reference document. We have to put some links for good tutorials for the general topic. Meanwhile, we'd better put a few details for some **commonly-used things in Seismic Tomography** so that the user without any experience can quickly know what to do and to use before they go to the links for details. For example, Tianjue will write some examples of some commonly-used commands.

**Comment by core-man** [comment]
Here is a temporal summary:

* [Computer & Programming](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/)
    * [Operating Systems](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/operating-systems.html): @core-man 
    * [Linux/macOS Basis](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/LinuxmacOS-basis.html): @core-man 
    * [Command Lines](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/command-lines.html): @tianjueli 
    * [Prgramming Languages](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/prgramming-languages.html): @core-man 
    * [Homework](https://migg-ntu.github.io/SeisTomo_Tutorials/basic-expertise-skills/homework.html):  @core-man 

- [Seismology](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/index.html#)
    - [resources](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/resources.html): @core-man 
    - [earthquake catalog](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/earthquake-catalog.html): @core-man 
    - [seismic station](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-station.html): @tianjueli 
    - [seismic waveform](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-waveform.html): @core-man 
    - [seismological tools](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-tools.html): @core-man 
    - [Homework](https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/homework.html): @core-man 

- [seismic data](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/index.html#)
    - [data downloading](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/data-downloading/index.html): @core-man 
    - [data processing](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/data-processing/index.html): @HouseJaay 
    - [plotting](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/plotting/index.html): @HouseJaay 
    - [Homework](https://migg-ntu.github.io/SeisTomo_Tutorials/seismic-data/homework.html): @core-man
